#
#  PyTrain: a library for controlling Lionel Legacy engines, trains, switches, and accessories.
#
#  Copyright (c) 2024-2026 Dave Swindell <pytraininfo.gmail.com>
#
#  SPDX-FileCopyrightText: 2024-2026 Dave Swindell <pytraininfo.gmail.com>
#  SPDX-License-Identifier: LGPL-3.0-only
#

from __future__ import annotations

import abc
from enum import IntEnum, unique
from typing import List

from ..command_def import Mixins
from ..tmcc2.tmcc2_constants import (
    TMCC2_SOUND_OFF_COMMAND,
    TMCC2_SOUND_ON_COMMAND,
    TMCC2CommandDef,
    TMCC2CommandPrefix,
    TMCC2EngineOpsEnum,
    TMCC2Enum,
)

"""
    Legacy/TMCC2 Multi-byte Command sequences
"""


class TMCC2MultiByteEnum(TMCC2Enum, TMCC2EngineOpsEnum):
    """
    Marker Interface for all TMCC2 enums
    """

    pass


"""
    Word #1 - Function indexes
"""
TMCC2_R4LC_INDEX_PREFIX: int = 0x40
TMCC2_VARIABLE_INDEX_PREFIX: int = 0x60
TMCC2_PARAMETER_INDEX_PREFIX: int = 0x70


@unique
class TMCCPrefixEnum(Mixins, IntEnum):
    R4LC = TMCC2_R4LC_INDEX_PREFIX
    VARIABLE = TMCC2_VARIABLE_INDEX_PREFIX
    PARAMETER = TMCC2_PARAMETER_INDEX_PREFIX


# Parameter indexes
TMCC2_PARAMETER_ASSIGNMENT_PARAMETER_INDEX: int = 0x71
TMCC2_RAIL_SOUNDS_DIALOG_TRIGGERS_PARAMETER_INDEX: int = 0x72
TMCC2_RAIL_SOUNDS_EFFECTS_TRIGGERS_PARAMETER_INDEX: int = 0x74
TMCC2_RAIL_SOUNDS_MASKING_CONTROL_PARAMETER_INDEX: int = 0x76
TMCC2_EFFECTS_CONTROLS_PARAMETER_INDEX: int = 0x7C
TMCC2_LIGHTING_CONTROLS_PARAMETER_INDEX: int = 0x7D

TMCC2_R4LC_PARAMETER_INDEX: int = 0x40
TMCC2_VARIABLE_LENGTH_PARAMETER_INDEX: int = 0x6F

TMCC2_TARGET_SPEED_PARAMETER_INDEX: int = 0x7B


@unique
class TMCC2ParameterIndex(Mixins, IntEnum):
    DIALOG_TRIGGERS = TMCC2_RAIL_SOUNDS_DIALOG_TRIGGERS_PARAMETER_INDEX
    EFFECTS_CONTROLS = TMCC2_EFFECTS_CONTROLS_PARAMETER_INDEX
    EFFECTS_TRIGGERS = TMCC2_RAIL_SOUNDS_EFFECTS_TRIGGERS_PARAMETER_INDEX
    LIGHTING_CONTROLS = TMCC2_LIGHTING_CONTROLS_PARAMETER_INDEX
    MASKING_CONTROLS = TMCC2_RAIL_SOUNDS_MASKING_CONTROL_PARAMETER_INDEX
    PARAMETER_ASSIGNMENT = TMCC2_PARAMETER_ASSIGNMENT_PARAMETER_INDEX
    R4LC = TMCC2_R4LC_PARAMETER_INDEX
    VARIABLE_LENGTH_COMMAND = TMCC2_VARIABLE_LENGTH_PARAMETER_INDEX
    TARGET_SPEED = TMCC2_TARGET_SPEED_PARAMETER_INDEX


class MultiByteCommandDef(TMCC2CommandDef):
    __metaclass__ = abc.ABCMeta

    def __init__(
        self,
        prefix: TMCC2ParameterIndex,
        command_bits: int,
        d_min: int = 0,
        d_max: int = 0,
        interval: int = None,
        noop: bool = False,
    ) -> None:
        super().__init__(command_bits, d_min=d_min, d_max=d_max, interval=interval, noop=noop)
        self._first_byte = TMCC2CommandPrefix.ENGINE
        self._second_byte = prefix


class TMCC2ParameterEnum(TMCC2MultiByteEnum):
    """
    Marker interface for all Parameter Data enums
    """

    pass


TMCC2_TARGET_SPEED_COMMAND = 0x00


class TMCC2EngineCommandEnumEx(TMCC2ParameterEnum):
    TARGET_SPEED = MultiByteCommandDef(
        TMCC2ParameterIndex.TARGET_SPEED,
        TMCC2_TARGET_SPEED_COMMAND,
        d_max=199,
        noop=True,
    )


"""
    Word #2 - RailSounds Dialog trigger controls (index 0x2)
"""
TMCC2_DIALOG_CONTROL_CONVENTIONAL_SHUTDOWN: int = 0x01
TMCC2_DIALOG_CONTROL_SCENE_TWO: int = 0x02
TMCC2_DIALOG_CONTROL_SCENE_SEVEN: int = 0x03
TMCC2_DIALOG_CONTROL_SCENE_FIVE: int = 0x04
TMCC2_DIALOG_CONTROL_SHORT_HORN: int = 0x05
TMCC2_DIALOG_CONTROL_TOWER_ENGINE_STARTUP: int = 0x06
TMCC2_DIALOG_CONTROL_ENGINEER_DEPARTURE_DENIED: int = 0x07
TMCC2_DIALOG_CONTROL_ENGINEER_DEPARTURE_GRANTED: int = 0x08
TMCC2_DIALOG_CONTROL_ENGINEER_HAVE_DEPARTED: int = 0x09
TMCC2_DIALOG_CONTROL_ENGINEER_ALL_CLEAR: int = 0x0A
TMCC2_DIALOG_CONTROL_TOWER_STOP_HOLD: int = 0x0B
TMCC2_DIALOG_CONTROL_TOWER_RESTRICTED_SPEED: int = 0x0C
TMCC2_DIALOG_CONTROL_TOWER_SLOW_SPEED: int = 0x0D
TMCC2_DIALOG_CONTROL_TOWER_MEDIUM_SPEED: int = 0x0E
TMCC2_DIALOG_CONTROL_TOWER_LIMITED_SPEED: int = 0x0F
TMCC2_DIALOG_CONTROL_TOWER_NORMAL_SPEED: int = 0x10
TMCC2_DIALOG_CONTROL_TOWER_HIGHBALL_SPEED: int = 0x11
TMCC2_DIALOG_CONTROL_ENGINEER_ARRIVING_SOON: int = 0x12
TMCC2_DIALOG_CONTROL_ENGINEER_HAVE_ARRIVED: int = 0x13
TMCC2_DIALOG_CONTROL_ENGINEER_SHUTDOWN: int = 0x14
TMCC2_DIALOG_CONTROL_ENGINEER_ID: int = 0x15
TMCC2_DIALOG_CONTROL_ENGINEER_ACK: int = 0x16
TMCC2_DIALOG_CONTROL_ENGINEER_STOP_SPEED_ACK: int = 0x17
TMCC2_DIALOG_CONTROL_ENGINEER_RESTRICTED_SPEED_ACK: int = 0x18
TMCC2_DIALOG_CONTROL_ENGINEER_SLOW_SPEED_ACK: int = 0x19
TMCC2_DIALOG_CONTROL_ENGINEER_MEDIUM_SPEED_ACK: int = 0x1A
TMCC2_DIALOG_CONTROL_ENGINEER_LIMITED_SPEED_ACK: int = 0x1B
TMCC2_DIALOG_CONTROL_ENGINEER_NORMAL_SPEED_ACK: int = 0x1C
TMCC2_DIALOG_CONTROL_ENGINEER_HIGHBALL_SPEED_ACK: int = 0x1D

TMCC2_DIALOG_CONTROL_ENGINEER_CONTEXT_DEPENDENT: int = 0x1E
TMCC2_DIALOG_CONTROL_EMERGENCY_CONTEXT_DEPENDENT: int = 0x1F
TMCC2_DIALOG_CONTROL_TOWER_CONTEXT_DEPENDENT: int = 0x20
TMCC2_DIALOG_CONTROL_TOWER_DEPARTURE_DENIED: int = 0x22
TMCC2_DIALOG_CONTROL_TOWER_DEPARTURE_GRANTED: int = 0x23
TMCC2_DIALOG_CONTROL_TOWER_DEPARTED: int = 0x24
TMCC2_DIALOG_CONTROL_TOWER_ALL_CLEAR: int = 0x25
TMCC2_DIALOG_CONTROL_TOWER_ARRIVING: int = 0x2D
# noinspection DuplicatedCode
TMCC2_DIALOG_CONTROL_TOWER_ARRIVED: int = 0x2E
TMCC2_DIALOG_CONTROL_TOWER_SHUT_DOWN: int = 0x2F

TMCC2_DIALOG_CONTROL_CONDUCTOR_ALL_ABOARD_A: int = 0x30

TMCC2_DIALOG_CONTROL_ENGINEER_ACK_STANDING_BY: int = 0x31
TMCC2_DIALOG_CONTROL_ENGINEER_ACK_CLEARED_TO_GO: int = 0x32
TMCC2_DIALOG_CONTROL_ENGINEER_ACK_CLEAR_AHEAD: int = 0x33
TMCC2_DIALOG_CONTROL_ENGINEER_ACK_CLEAR_INBOUND: int = 0x34
TMCC2_DIALOG_CONTROL_ENGINEER_ACK_WELCOME_BACK: int = 0x35
TMCC2_DIALOG_CONTROL_ENGINEER_ACK_ID: int = 0x36

TMCC2_DIALOG_CONTROL_ENGINEER_FUEL_LEVEL: int = 0x3D
TMCC2_DIALOG_CONTROL_ENGINEER_FUEL_REFILLED: int = 0x3E
TMCC2_DIALOG_CONTROL_ENGINEER_SPEED: int = 0x3F
TMCC2_DIALOG_CONTROL_ENGINEER_WATER_LEVEL: int = 0x40
TMCC2_DIALOG_CONTROL_ENGINEER_WATER_REFILLED: int = 0x41

TMCC2_DIALOG_CONTROL_SEQUENCE_CONTROL_OFF: int = 0x50
TMCC2_DIALOG_CONTROL_SEQUENCE_CONTROL_ON: int = 0x51
TMCC2_DIALOG_CONTROL_SEQUENCE_CONTROL_CLEAR: int = 0x52
TMCC2_DIALOG_CONTROL_SEQUENCE_CONTROL_DEPARTED: int = 0x53
TMCC2_DIALOG_CONTROL_SEQUENCE_CONTROL_TRANSIT: int = 0x54
TMCC2_DIALOG_CONTROL_SEQUENCE_CONTROL_MAX_SPEED: int = 0x55

TMCC2_DIALOG_CONTROL_CONDUCTOR_NEXT_STOP: int = 0x68
TMCC2_DIALOG_CONTROL_CONDUCTOR_WATCH_YOUR_STEP: int = 0x69
TMCC2_DIALOG_CONTROL_CONDUCTOR_ALL_ABOARD: int = 0x6A
TMCC2_DIALOG_CONTROL_CONDUCTOR_TICKETS_PLEASE: int = 0x6B
TMCC2_DIALOG_CONTROL_CONDUCTOR_PREMATURE_STOP: int = 0x6C

TMCC2_DIALOG_CONTROL_STEWARD_WELCOME_ABOARD: int = 0x6D
TMCC2_DIALOG_CONTROL_STEWARD_FIRST_SEATING: int = 0x6E
TMCC2_DIALOG_CONTROL_STEWARD_SECOND_SEATING: int = 0x6F
TMCC2_DIALOG_CONTROL_STEWARD_LOUNGE_CAR_OPEN: int = 0x70

TMCC2_DIALOG_CONTROL_STATION_ARRIVING: int = 0x71
TMCC2_DIALOG_CONTROL_STATION_ARRIVED: int = 0x72
TMCC2_DIALOG_CONTROL_STATION_BOARDING: int = 0x73
TMCC2_DIALOG_CONTROL_STATION_DEPARTING: int = 0x74

TMCC2_DIALOG_CONTROL_PASSENGER_CAR_STARTUP: int = 0x75
TMCC2_DIALOG_CONTROL_PASSENGER_CAR_SHUTDOWN: int = 0x76

TMCC2_DIALOG_CONTROL_SPECIAL_GUEST_ENABLED: int = 0x7D
TMCC2_DIALOG_CONTROL_SPECIAL_GUEST_DISABLED: int = 0x7E


class RailSoundsCommandDef(MultiByteCommandDef):
    def __init__(
        self,
        command_bits: int,
        d_min: int = 0,
        d_max: int = 0,
        interval: int = None,
        noop: bool = False,
    ) -> None:
        super().__init__(
            TMCC2ParameterIndex.DIALOG_TRIGGERS,
            command_bits,
            d_min=d_min,
            d_max=d_max,
            interval=interval,
            noop=noop,
        )


@unique
class TMCC2RailSoundsDialogControl(TMCC2ParameterEnum):
    CONVENTIONAL_SHUTDOWN = RailSoundsCommandDef(TMCC2_DIALOG_CONTROL_CONVENTIONAL_SHUTDOWN)
    SCENE_TWO = RailSoundsCommandDef(TMCC2_DIALOG_CONTROL_SCENE_TWO)
    SCENE_FIVE = RailSoundsCommandDef(TMCC2_DIALOG_CONTROL_SCENE_FIVE)
    SCENE_SEVEN = RailSoundsCommandDef(TMCC2_DIALOG_CONTROL_SCENE_SEVEN)
    SHORT_HORN = RailSoundsCommandDef(TMCC2_DIALOG_CONTROL_SHORT_HORN)
    TOWER_STARTUP = RailSoundsCommandDef(TMCC2_DIALOG_CONTROL_TOWER_ENGINE_STARTUP)
    ENGINEER_DEPARTURE_DENIED = RailSoundsCommandDef(TMCC2_DIALOG_CONTROL_ENGINEER_DEPARTURE_DENIED)
    ENGINEER_DEPARTURE_GRANTED = RailSoundsCommandDef(TMCC2_DIALOG_CONTROL_ENGINEER_DEPARTURE_GRANTED)
    ENGINEER_DEPARTED = RailSoundsCommandDef(TMCC2_DIALOG_CONTROL_ENGINEER_HAVE_DEPARTED)
    ENGINEER_ALL_CLEAR = RailSoundsCommandDef(TMCC2_DIALOG_CONTROL_ENGINEER_ALL_CLEAR)
    TOWER_SPEED_STOP_HOLD = RailSoundsCommandDef(TMCC2_DIALOG_CONTROL_TOWER_STOP_HOLD)
    TOWER_SPEED_RESTRICTED = RailSoundsCommandDef(TMCC2_DIALOG_CONTROL_TOWER_RESTRICTED_SPEED)
    TOWER_SPEED_SLOW = RailSoundsCommandDef(TMCC2_DIALOG_CONTROL_TOWER_SLOW_SPEED)
    TOWER_SPEED_MEDIUM = RailSoundsCommandDef(TMCC2_DIALOG_CONTROL_TOWER_MEDIUM_SPEED)
    TOWER_SPEED_LIMITED = RailSoundsCommandDef(TMCC2_DIALOG_CONTROL_TOWER_LIMITED_SPEED)
    TOWER_SPEED_NORMAL = RailSoundsCommandDef(TMCC2_DIALOG_CONTROL_TOWER_NORMAL_SPEED)
    TOWER_SPEED_HIGHBALL = RailSoundsCommandDef(TMCC2_DIALOG_CONTROL_TOWER_HIGHBALL_SPEED)
    ENGINEER_ARRIVING = RailSoundsCommandDef(TMCC2_DIALOG_CONTROL_ENGINEER_ARRIVING_SOON)
    ENGINEER_ARRIVED = RailSoundsCommandDef(TMCC2_DIALOG_CONTROL_ENGINEER_HAVE_ARRIVED)
    ENGINEER_SHUTDOWN = RailSoundsCommandDef(TMCC2_DIALOG_CONTROL_ENGINEER_SHUTDOWN)
    ENGINEER_ID = RailSoundsCommandDef(TMCC2_DIALOG_CONTROL_ENGINEER_ID)
    ENGINEER_ACK = RailSoundsCommandDef(TMCC2_DIALOG_CONTROL_ENGINEER_ACK)
    ENGINEER_SPEED_STOP_HOLD = RailSoundsCommandDef(TMCC2_DIALOG_CONTROL_ENGINEER_STOP_SPEED_ACK)
    ENGINEER_SPEED_RESTRICTED = RailSoundsCommandDef(TMCC2_DIALOG_CONTROL_ENGINEER_RESTRICTED_SPEED_ACK)
    ENGINEER_SPEED_SLOW = RailSoundsCommandDef(TMCC2_DIALOG_CONTROL_ENGINEER_SLOW_SPEED_ACK)
    ENGINEER_SPEED_MEDIUM = RailSoundsCommandDef(TMCC2_DIALOG_CONTROL_ENGINEER_MEDIUM_SPEED_ACK)
    ENGINEER_SPEED_LIMITED = RailSoundsCommandDef(TMCC2_DIALOG_CONTROL_ENGINEER_LIMITED_SPEED_ACK)
    ENGINEER_SPEED_NORMAL = RailSoundsCommandDef(TMCC2_DIALOG_CONTROL_ENGINEER_NORMAL_SPEED_ACK)
    ENGINEER_SPEED_HIGHBALL = RailSoundsCommandDef(TMCC2_DIALOG_CONTROL_ENGINEER_HIGHBALL_SPEED_ACK)
    ENGINEER_CONTEXT_DEPENDENT = RailSoundsCommandDef(TMCC2_DIALOG_CONTROL_ENGINEER_CONTEXT_DEPENDENT)
    EMERGENCY_CONTEXT_DEPENDENT = RailSoundsCommandDef(TMCC2_DIALOG_CONTROL_EMERGENCY_CONTEXT_DEPENDENT)
    TOWER_CONTEXT_DEPENDENT = RailSoundsCommandDef(TMCC2_DIALOG_CONTROL_TOWER_CONTEXT_DEPENDENT)
    TOWER_DEPARTURE_DENIED = RailSoundsCommandDef(TMCC2_DIALOG_CONTROL_TOWER_DEPARTURE_DENIED)
    TOWER_DEPARTURE_GRANTED = RailSoundsCommandDef(TMCC2_DIALOG_CONTROL_TOWER_DEPARTURE_GRANTED)
    TOWER_DEPARTED = RailSoundsCommandDef(TMCC2_DIALOG_CONTROL_TOWER_DEPARTED)
    TOWER_ALL_CLEAR = RailSoundsCommandDef(TMCC2_DIALOG_CONTROL_TOWER_ALL_CLEAR)
    TOWER_ARRIVING = RailSoundsCommandDef(TMCC2_DIALOG_CONTROL_TOWER_ARRIVING)
    TOWER_ARRIVED = RailSoundsCommandDef(TMCC2_DIALOG_CONTROL_TOWER_ARRIVED)
    TOWER_SHUTDOWN = RailSoundsCommandDef(TMCC2_DIALOG_CONTROL_TOWER_SHUT_DOWN)

    ENGINEER_ACK_CLEARED = RailSoundsCommandDef(TMCC2_DIALOG_CONTROL_ENGINEER_ACK_CLEARED_TO_GO)
    ENGINEER_ACK_CLEAR_AHEAD = RailSoundsCommandDef(TMCC2_DIALOG_CONTROL_ENGINEER_ACK_CLEAR_AHEAD)
    ENGINEER_ACK_CLEAR_INBOUND = RailSoundsCommandDef(TMCC2_DIALOG_CONTROL_ENGINEER_ACK_CLEAR_INBOUND)
    ENGINEER_ACK_ID = RailSoundsCommandDef(TMCC2_DIALOG_CONTROL_ENGINEER_ACK_ID)
    ENGINEER_ACK_STAND_BY = RailSoundsCommandDef(TMCC2_DIALOG_CONTROL_ENGINEER_ACK_STANDING_BY)
    ENGINEER_ACK_WELCOME_BACK = RailSoundsCommandDef(TMCC2_DIALOG_CONTROL_ENGINEER_ACK_WELCOME_BACK)
    ENGINEER_FUEL_LEVEL = RailSoundsCommandDef(TMCC2_DIALOG_CONTROL_ENGINEER_FUEL_LEVEL)
    ENGINEER_FUEL_REFILLED = RailSoundsCommandDef(TMCC2_DIALOG_CONTROL_ENGINEER_FUEL_REFILLED)
    ENGINEER_SPEED = RailSoundsCommandDef(TMCC2_DIALOG_CONTROL_ENGINEER_SPEED)
    ENGINEER_WATER_LEVEL = RailSoundsCommandDef(TMCC2_DIALOG_CONTROL_ENGINEER_WATER_LEVEL)
    ENGINEER_WATER_REFILLED = RailSoundsCommandDef(TMCC2_DIALOG_CONTROL_ENGINEER_WATER_REFILLED)

    CONDUCTOR_NEXT_STOP = RailSoundsCommandDef(TMCC2_DIALOG_CONTROL_CONDUCTOR_NEXT_STOP)
    CONDUCTOR_WATCH_YOUR_STEP = RailSoundsCommandDef(TMCC2_DIALOG_CONTROL_CONDUCTOR_WATCH_YOUR_STEP)
    CONDUCTOR_ALL_ABOARD = RailSoundsCommandDef(TMCC2_DIALOG_CONTROL_CONDUCTOR_ALL_ABOARD)
    CONDUCTOR_TICKETS_PLEASE = RailSoundsCommandDef(TMCC2_DIALOG_CONTROL_CONDUCTOR_TICKETS_PLEASE)
    CONDUCTOR_PREMATURE_STOP = RailSoundsCommandDef(TMCC2_DIALOG_CONTROL_CONDUCTOR_PREMATURE_STOP)

    STEWARD_WELCOME_ABOARD = RailSoundsCommandDef(TMCC2_DIALOG_CONTROL_STEWARD_WELCOME_ABOARD)
    STEWARD_FIRST_SEATING = RailSoundsCommandDef(TMCC2_DIALOG_CONTROL_STEWARD_FIRST_SEATING)
    STEWARD_SECOND_SEATING = RailSoundsCommandDef(TMCC2_DIALOG_CONTROL_STEWARD_SECOND_SEATING)
    STEWARD_LOUNGE_CAR_OPEN = RailSoundsCommandDef(TMCC2_DIALOG_CONTROL_STEWARD_LOUNGE_CAR_OPEN)

    STATION_ARRIVING = RailSoundsCommandDef(TMCC2_DIALOG_CONTROL_STATION_ARRIVING)
    STATION_ARRIVED = RailSoundsCommandDef(TMCC2_DIALOG_CONTROL_STATION_ARRIVED)
    STATION_BOARDING = RailSoundsCommandDef(TMCC2_DIALOG_CONTROL_STATION_BOARDING)
    STATION_DEPARTING = RailSoundsCommandDef(TMCC2_DIALOG_CONTROL_STATION_DEPARTING)

    PASSENGER_CAR_STARTUP = RailSoundsCommandDef(TMCC2_DIALOG_CONTROL_PASSENGER_CAR_STARTUP)
    PASSENGER_CAR_SHUTDOWN = RailSoundsCommandDef(TMCC2_DIALOG_CONTROL_PASSENGER_CAR_SHUTDOWN)

    SPECIAL_GUEST_ENABLED = RailSoundsCommandDef(TMCC2_DIALOG_CONTROL_SPECIAL_GUEST_ENABLED)
    SPECIAL_GUEST_DISABLED = RailSoundsCommandDef(TMCC2_DIALOG_CONTROL_SPECIAL_GUEST_DISABLED)

    SEQUENCE_OFF = RailSoundsCommandDef(TMCC2_DIALOG_CONTROL_SEQUENCE_CONTROL_OFF)
    SEQUENCE_ON = RailSoundsCommandDef(TMCC2_DIALOG_CONTROL_SEQUENCE_CONTROL_ON)
    SEQUENCE_CLEAR = RailSoundsCommandDef(TMCC2_DIALOG_CONTROL_SEQUENCE_CONTROL_CLEAR)
    SEQUENCE_DEPARTED = RailSoundsCommandDef(TMCC2_DIALOG_CONTROL_SEQUENCE_CONTROL_DEPARTED)
    SEQUENCE_TRANSIT = RailSoundsCommandDef(TMCC2_DIALOG_CONTROL_SEQUENCE_CONTROL_TRANSIT)
    SEQUENCE_MAX_SPEED = RailSoundsCommandDef(TMCC2_DIALOG_CONTROL_SEQUENCE_CONTROL_MAX_SPEED)


"""
    Word #2 - RailSounds Effects trigger controls (index 0x4)
"""
TMCC2_RS_EFFECTS_PRIME_MOVER_OFF: int = 0x10
TMCC2_RS_EFFECTS_PRIME_MOVER_ON: int = 0x11
TMCC2_RS_EFFECTS_MASTER_VOLUME_DOWN: int = 0x12
TMCC2_RS_EFFECTS_MASTER_VOLUME_UP: int = 0x13
TMCC2_RS_EFFECTS_BLEND_VOLUME_DOWN: int = 0x14
TMCC2_RS_EFFECTS_BLEND_VOLUME_UP: int = 0x15
TMCC2_RS_EFFECTS_CYLINDER_CLEARING_ON: int = 0x20
TMCC2_RS_EFFECTS_CYLINDER_CLEARING_OFF: int = 0x21
TMCC2_RS_EFFECTS_WHEEL_SLIP_TRIGGER: int = 0x22
TMCC2_RS_EFFECTS_STANDBY_WARNING_BELL: int = 0x23
TMCC2_RS_EFFECTS_STANDBY_MODE_DISABLE: int = 0x24
TMCC2_RS_EFFECTS_STANDBY_MODE_ENABLE: int = 0x25
TMCC2_RS_EFFECTS_FORCE_COUPLER_IMPACT_COMPRESS: int = 0x26
TMCC2_RS_EFFECTS_FORCE_COUPLER_IMPACT_STRETCH: int = 0x27
TMCC2_RS_EFFECTS_CIRCUIT_BREAKER_MAIN_LIGHTS: int = 0x28
TMCC2_RS_EFFECTS_CIRCUIT_BREAKER_CAB_LIGHTS: int = 0x29
TMCC2_RS_EFFECTS_CIRCUIT_BREAKER_WORK_LIGHTS: int = 0x2A
TMCC2_RS_EFFECTS_SEQUENCE_CONTROL_OFF: int = 0x2C
TMCC2_RS_EFFECTS_SEQUENCE_CONTROL_ON: int = 0x2D

TMCC2_RS_EFFECTS_RESET_ODOMETER: int = 0x30
TMCC2_RS_EFFECTS_INCREMENT_FUEL_LOAD: int = 0x31

TMCC2_RS_EFFECTS_SOUND_SYSTEM_OFF = TMCC2_SOUND_OFF_COMMAND
TMCC2_RS_EFFECTS_SOUND_SYSTEM_ON = TMCC2_SOUND_ON_COMMAND


class EffectsTriggersCommandDef(MultiByteCommandDef):
    def __init__(
        self,
        command_bits: int,
        d_min: int = 0,
        d_max: int = 0,
        interval: int = None,
        noop: bool = False,
    ) -> None:
        super().__init__(
            TMCC2ParameterIndex.EFFECTS_TRIGGERS,
            command_bits,
            d_min=d_min,
            d_max=d_max,
            interval=interval,
            noop=noop,
        )


@unique
class TMCC2RailSoundsEffectsControl(TMCC2ParameterEnum):
    ADD_FUEL = EffectsTriggersCommandDef(TMCC2_RS_EFFECTS_INCREMENT_FUEL_LOAD)
    BLEND_DOWN = EffectsTriggersCommandDef(TMCC2_RS_EFFECTS_BLEND_VOLUME_DOWN)
    BLEND_UP = EffectsTriggersCommandDef(TMCC2_RS_EFFECTS_BLEND_VOLUME_UP)
    CAB_BREAKER = EffectsTriggersCommandDef(TMCC2_RS_EFFECTS_CIRCUIT_BREAKER_CAB_LIGHTS)
    COUPLER_COMPRESS = EffectsTriggersCommandDef(TMCC2_RS_EFFECTS_FORCE_COUPLER_IMPACT_COMPRESS)
    COUPLER_STRETCH = EffectsTriggersCommandDef(TMCC2_RS_EFFECTS_FORCE_COUPLER_IMPACT_STRETCH)
    CYLINDER_OFF = EffectsTriggersCommandDef(TMCC2_RS_EFFECTS_CYLINDER_CLEARING_OFF)
    CYLINDER_ON = EffectsTriggersCommandDef(TMCC2_RS_EFFECTS_CYLINDER_CLEARING_ON)
    MAIN_BREAKER = EffectsTriggersCommandDef(TMCC2_RS_EFFECTS_CIRCUIT_BREAKER_MAIN_LIGHTS)
    PRIME_OFF = EffectsTriggersCommandDef(TMCC2_RS_EFFECTS_PRIME_MOVER_OFF)
    PRIME_ON = EffectsTriggersCommandDef(TMCC2_RS_EFFECTS_PRIME_MOVER_ON)
    RESET_ODOMETER = EffectsTriggersCommandDef(TMCC2_RS_EFFECTS_RESET_ODOMETER)
    SEQUENCE_CONTROL_OFF = EffectsTriggersCommandDef(TMCC2_RS_EFFECTS_SEQUENCE_CONTROL_OFF)
    SEQUENCE_CONTROL_ON = EffectsTriggersCommandDef(TMCC2_RS_EFFECTS_SEQUENCE_CONTROL_ON)
    STANDBY_BELL = EffectsTriggersCommandDef(TMCC2_RS_EFFECTS_STANDBY_WARNING_BELL)
    STANDBY_DISABLE = EffectsTriggersCommandDef(TMCC2_RS_EFFECTS_STANDBY_MODE_DISABLE)
    STANDBY_ENABLE = EffectsTriggersCommandDef(TMCC2_RS_EFFECTS_STANDBY_MODE_ENABLE)
    VOLUME_DOWN_RS = EffectsTriggersCommandDef(TMCC2_RS_EFFECTS_MASTER_VOLUME_DOWN)
    VOLUME_UP_RS = EffectsTriggersCommandDef(TMCC2_RS_EFFECTS_MASTER_VOLUME_UP)
    WHEEL_SLIP = EffectsTriggersCommandDef(TMCC2_RS_EFFECTS_WHEEL_SLIP_TRIGGER)
    WORK_BREAKER = EffectsTriggersCommandDef(TMCC2_RS_EFFECTS_CIRCUIT_BREAKER_WORK_LIGHTS)


"""
    Word #2 - Sound masking controls (index 0x6)
"""
TMCC2_MASKING_DIALOG_NC_SIGNAL_NC: int = 0x00
TMCC2_MASKING_DIALOG_PLAY_ALWAYS_SIGNAL_NC: int = 0x01
TMCC2_MASKING_DIALOG_PLAY_NEVER_SIGNAL_NC: int = 0x02
TMCC2_MASKING_DIALOG_DEFAULT_SIGNAL_NC: int = 0x03

TMCC2_MASKING_DIALOG_NC_SIGNAL_PLAY_ALWAYS: int = 0x04
TMCC2_MASKING_DIALOG_PLAY_ALWAYS_SIGNAL_PLAY_ALWAYS: int = 0x05
TMCC2_MASKING_DIALOG_PLAY_NEVER_SIGNAL_PLAY_ALWAYS: int = 0x06
TMCC2_MASKING_DIALOG_DEFAULT_SIGNAL_PLAY_ALWAYS: int = 0x07

TMCC2_MASKING_DIALOG_NC_SIGNAL_PLAY_NEVER: int = 0x08
TMCC2_MASKING_DIALOG_PLAY_ALWAYS_SIGNAL_PLAY_NEVER: int = 0x09
TMCC2_MASKING_DIALOG_PLAY_NEVER_SIGNAL_PLAY_NEVER: int = 0x0A
TMCC2_MASKING_DIALOG_DEFAULT_SIGNAL_PLAY_NEVER: int = 0x0B

TMCC2_MASKING_DIALOG_NC_SIGNAL_DEFAULT: int = 0x0C
TMCC2_MASKING_DIALOG_PLAY_ALWAYS_SIGNAL_DEFAULT: int = 0x0D
TMCC2_MASKING_DIALOG_PLAY_NEVER_SIGNAL_DEFAULT: int = 0x0E
TMCC2_MASKING_DIALOG_DEFAULT_SIGNAL_DEFAULT: int = 0x0F

TMCC2_BRAKE_SQUEAL_DISABLE: int = 0x20
TMCC2_BRAKE_SQUEAL_ENABLE: int = 0x21


class MaskingControlCommandDef(MultiByteCommandDef):
    def __init__(
        self,
        command_bits: int,
        d_min: int = 0,
        d_max: int = 0,
        interval: int = None,
        noop: bool = False,
    ) -> None:
        super().__init__(
            TMCC2ParameterIndex.MASKING_CONTROLS,
            command_bits,
            d_min=d_min,
            d_max=d_max,
            interval=interval,
            noop=noop,
        )


@unique
class TMCC2MaskingControl(TMCC2ParameterEnum):
    NC_NC = MaskingControlCommandDef(TMCC2_MASKING_DIALOG_NC_SIGNAL_NC)
    ALWAYS_NC = MaskingControlCommandDef(TMCC2_MASKING_DIALOG_PLAY_ALWAYS_SIGNAL_NC)
    NEVER_NC = MaskingControlCommandDef(TMCC2_MASKING_DIALOG_PLAY_NEVER_SIGNAL_NC)
    DEFAULT_NC = MaskingControlCommandDef(TMCC2_MASKING_DIALOG_DEFAULT_SIGNAL_NC)
    NC_ALWAYS = MaskingControlCommandDef(TMCC2_MASKING_DIALOG_NC_SIGNAL_PLAY_ALWAYS)
    ALWAYS_ALWAYS = MaskingControlCommandDef(TMCC2_MASKING_DIALOG_PLAY_ALWAYS_SIGNAL_PLAY_ALWAYS)
    NEVER_ALWAYS = MaskingControlCommandDef(TMCC2_MASKING_DIALOG_PLAY_NEVER_SIGNAL_PLAY_ALWAYS)
    DEFAULT_ALWAYS = MaskingControlCommandDef(TMCC2_MASKING_DIALOG_DEFAULT_SIGNAL_PLAY_ALWAYS)
    NC_NEVER = MaskingControlCommandDef(TMCC2_MASKING_DIALOG_NC_SIGNAL_PLAY_NEVER)
    ALWAYS_NEVER = MaskingControlCommandDef(TMCC2_MASKING_DIALOG_PLAY_ALWAYS_SIGNAL_PLAY_NEVER)
    NEVER_NEVER = MaskingControlCommandDef(TMCC2_MASKING_DIALOG_PLAY_NEVER_SIGNAL_PLAY_NEVER)
    DEFAULT_NEVER = MaskingControlCommandDef(TMCC2_MASKING_DIALOG_DEFAULT_SIGNAL_PLAY_NEVER)
    NC_DEFAULT = MaskingControlCommandDef(TMCC2_MASKING_DIALOG_NC_SIGNAL_DEFAULT)
    PLAY_DEFAULT = MaskingControlCommandDef(TMCC2_MASKING_DIALOG_PLAY_ALWAYS_SIGNAL_DEFAULT)
    NEVER_DEFAULT = MaskingControlCommandDef(TMCC2_MASKING_DIALOG_PLAY_NEVER_SIGNAL_DEFAULT)
    DEFAULT_DEFAULT = MaskingControlCommandDef(TMCC2_MASKING_DIALOG_DEFAULT_SIGNAL_DEFAULT)
    BRAKE_SQUEAL_ENABLE = MaskingControlCommandDef(TMCC2_BRAKE_SQUEAL_ENABLE)
    BRAKE_SQUEAL_DISABLE = MaskingControlCommandDef(TMCC2_BRAKE_SQUEAL_DISABLE)


"""
    Word #2 - Effects controls (index 0xC)
"""
TMCC2_EFFECTS_CONTROL_SMOKE_OFF: int = 0x00
TMCC2_EFFECTS_CONTROL_SMOKE_LOW: int = 0x01
TMCC2_EFFECTS_CONTROL_SMOKE_MEDIUM: int = 0x02
TMCC2_EFFECTS_CONTROL_SMOKE_HIGH: int = 0x03
TMCC2_EFFECTS_CONTROL_PANTOGRAPH_FRONT_UP_CAB2: int = 0x10
TMCC2_EFFECTS_CONTROL_PANTOGRAPH_FRONT_DOWN_CAB2: int = 0x11
TMCC2_EFFECTS_CONTROL_PANTOGRAPH_REAR_UP_CAB2: int = 0x12
TMCC2_EFFECTS_CONTROL_PANTOGRAPH_REAR_DOWN_CAB2: int = 0x13
TMCC2_EFFECTS_CONTROL_PANTOGRAPH_FRONT_DOWN: int = 0x18
TMCC2_EFFECTS_CONTROL_PANTOGRAPH_FRONT_UP: int = 0x19
TMCC2_EFFECTS_CONTROL_PANTOGRAPH_REAR_DOWN: int = 0x1A
TMCC2_EFFECTS_CONTROL_PANTOGRAPH_REAR_UP: int = 0x1B
TMCC2_EFFECTS_CONTROL_PANTOGRAPH_BOTH_DOWN: int = 0x1E
TMCC2_EFFECTS_CONTROL_PANTOGRAPH_BOTH_UP: int = 0x1F
TMCC2_EFFECTS_CONTROL_SUBWAY_LEFT_DOOR_OPEN_CAB2: int = 0x20
TMCC2_EFFECTS_CONTROL_SUBWAY_LEFT_DOOR_CLOSE_CAB2: int = 0x21
TMCC2_EFFECTS_CONTROL_SUBWAY_RIGHT_DOOR_OPEN_CAB2: int = 0x22
TMCC2_EFFECTS_CONTROL_SUBWAY_RIGHT_DOOR_CLOSE_CAB2: int = 0x23
TMCC2_EFFECTS_CONTROL_SUBWAY_LEFT_DOOR_CLOSE: int = 0x28
TMCC2_EFFECTS_CONTROL_SUBWAY_LEFT_DOOR_OPEN: int = 0x29
TMCC2_EFFECTS_CONTROL_SUBWAY_RIGHT_DOOR_CLOSE: int = 0x2A
TMCC2_EFFECTS_CONTROL_SUBWAY_RIGHT_DOOR_OPEN: int = 0x2B
TMCC2_EFFECTS_CONTROL_SUBWAY_BOTH_DOOR_CLOSE: int = 0x2E
TMCC2_EFFECTS_CONTROL_SUBWAY_BOTH_DOOR_OPEN: int = 0x2F
TMCC2_EFFECTS_CONTROL_STOCK_CAR_OPTION_ONE_ON: int = 0x30
TMCC2_EFFECTS_CONTROL_STOCK_CAR_OPTION_ONE_OFF: int = 0x31
TMCC2_EFFECTS_CONTROL_STOCK_CAR_OPTION_TWO_ON: int = 0x32
TMCC2_EFFECTS_CONTROL_STOCK_CAR_OPTION_TWO_OFF: int = 0x33
TMCC2_EFFECTS_CONTROL_STOCK_CAR_LOAD: int = 0x34
TMCC2_EFFECTS_CONTROL_STOCK_CAR_UNLOAD: int = 0x35
TMCC2_EFFECTS_CONTROL_STOCK_CAR_FRED_ON: int = 0x36
TMCC2_EFFECTS_CONTROL_STOCK_CAR_FRED_OFF: int = 0x37
TMCC2_EFFECTS_CONTROL_STOCK_CAR_FLAT_WHEEL_ON: int = 0x38
TMCC2_EFFECTS_CONTROL_STOCK_CAR_FLAT_WHEEL_OFF: int = 0x39
TMCC2_EFFECTS_CONTROL_STOCK_CAR_GAME_ON: int = 0x3A
TMCC2_EFFECTS_CONTROL_STOCK_CAR_GAME_OFF: int = 0x3B
TMCC2_EFFECTS_CONTROL_SCENE_ZERO: int = 0x3C
TMCC2_EFFECTS_CONTROL_SCENE_ONE: int = 0x3D
TMCC2_EFFECTS_CONTROL_SCENE_TWO: int = 0x3E
TMCC2_EFFECTS_CONTROL_SCENE_THREE: int = 0x3F
TMCC2_EFFECTS_CONTROL_COAL_EMPTY: int = 0x50
TMCC2_EFFECTS_CONTROL_COAL_FULL: int = 0x51
TMCC2_EFFECTS_CONTROL_COAL_EMPTYING: int = 0x52
TMCC2_EFFECTS_CONTROL_COAL_FILLING: int = 0x53


class EffectsControlCommandDef(MultiByteCommandDef):
    def __init__(
        self,
        command_bits: int,
        d_min: int = 0,
        d_max: int = 0,
        interval: int = None,
        noop: bool = False,
    ) -> None:
        super().__init__(
            TMCC2ParameterIndex.EFFECTS_CONTROLS,
            command_bits,
            d_min=d_min,
            d_max=d_max,
            interval=interval,
            noop=noop,
        )


@unique
class TMCC2EffectsControl(TMCC2ParameterEnum):
    PANTO_FRONT_DOWN_CAB2 = EffectsControlCommandDef(TMCC2_EFFECTS_CONTROL_PANTOGRAPH_FRONT_DOWN_CAB2)
    PANTO_FRONT_UP_CAB2 = EffectsControlCommandDef(TMCC2_EFFECTS_CONTROL_PANTOGRAPH_FRONT_UP_CAB2)
    PANTO_REAR_DOWN_CAB2 = EffectsControlCommandDef(TMCC2_EFFECTS_CONTROL_PANTOGRAPH_REAR_DOWN_CAB2)
    PANTO_REAR_UP_CAB2 = EffectsControlCommandDef(TMCC2_EFFECTS_CONTROL_PANTOGRAPH_REAR_UP_CAB2)
    PANTO_FRONT_DOWN = EffectsControlCommandDef(TMCC2_EFFECTS_CONTROL_PANTOGRAPH_FRONT_DOWN)
    PANTO_FRONT_UP = EffectsControlCommandDef(TMCC2_EFFECTS_CONTROL_PANTOGRAPH_FRONT_UP)
    PANTO_REAR_DOWN = EffectsControlCommandDef(TMCC2_EFFECTS_CONTROL_PANTOGRAPH_REAR_DOWN)
    PANTO_REAR_UP = EffectsControlCommandDef(TMCC2_EFFECTS_CONTROL_PANTOGRAPH_REAR_UP)
    PANTO_BOTH_DOWN = EffectsControlCommandDef(TMCC2_EFFECTS_CONTROL_PANTOGRAPH_BOTH_DOWN)
    PANTO_BOTH_UP = EffectsControlCommandDef(TMCC2_EFFECTS_CONTROL_PANTOGRAPH_BOTH_UP)
    SMOKE_HIGH = EffectsControlCommandDef(TMCC2_EFFECTS_CONTROL_SMOKE_HIGH)
    SMOKE_LOW = EffectsControlCommandDef(TMCC2_EFFECTS_CONTROL_SMOKE_LOW)
    SMOKE_MEDIUM = EffectsControlCommandDef(TMCC2_EFFECTS_CONTROL_SMOKE_MEDIUM)
    SMOKE_OFF = EffectsControlCommandDef(TMCC2_EFFECTS_CONTROL_SMOKE_OFF)
    STOCK_SCENE_ZERO = EffectsControlCommandDef(TMCC2_EFFECTS_CONTROL_SCENE_ZERO)
    STOCK_SCENE_ONE = EffectsControlCommandDef(TMCC2_EFFECTS_CONTROL_SCENE_ONE)
    STOCK_SCENE_TWO = EffectsControlCommandDef(TMCC2_EFFECTS_CONTROL_SCENE_TWO)
    STOCK_SCENE_THREE = EffectsControlCommandDef(TMCC2_EFFECTS_CONTROL_SCENE_THREE)
    STOCK_FRED_OFF = EffectsControlCommandDef(TMCC2_EFFECTS_CONTROL_STOCK_CAR_FRED_OFF)
    STOCK_FRED_ON = EffectsControlCommandDef(TMCC2_EFFECTS_CONTROL_STOCK_CAR_FRED_ON)
    STOCK_GAME_OFF = EffectsControlCommandDef(TMCC2_EFFECTS_CONTROL_STOCK_CAR_GAME_OFF)
    STOCK_GAME_ON = EffectsControlCommandDef(TMCC2_EFFECTS_CONTROL_STOCK_CAR_GAME_ON)
    STOCK_LOAD = EffectsControlCommandDef(TMCC2_EFFECTS_CONTROL_STOCK_CAR_LOAD)
    STOCK_OPTION_ONE_OFF = EffectsControlCommandDef(TMCC2_EFFECTS_CONTROL_STOCK_CAR_OPTION_ONE_OFF)
    STOCK_OPTION_ONE_ON = EffectsControlCommandDef(TMCC2_EFFECTS_CONTROL_STOCK_CAR_OPTION_ONE_ON)
    STOCK_OPTION_TWO_OFF = EffectsControlCommandDef(TMCC2_EFFECTS_CONTROL_STOCK_CAR_OPTION_TWO_OFF)
    STOCK_OPTION_TWO_ON = EffectsControlCommandDef(TMCC2_EFFECTS_CONTROL_STOCK_CAR_OPTION_TWO_ON)
    STOCK_UNLOAD = EffectsControlCommandDef(TMCC2_EFFECTS_CONTROL_STOCK_CAR_UNLOAD)
    STOCK_WHEEL_OFF = EffectsControlCommandDef(TMCC2_EFFECTS_CONTROL_STOCK_CAR_FLAT_WHEEL_OFF)
    STOCK_WHEEL_ON = EffectsControlCommandDef(TMCC2_EFFECTS_CONTROL_STOCK_CAR_FLAT_WHEEL_ON)
    SUBWAY_LEFT_DOOR_CLOSE = EffectsControlCommandDef(TMCC2_EFFECTS_CONTROL_SUBWAY_LEFT_DOOR_CLOSE)
    SUBWAY_LEFT_DOOR_OPEN = EffectsControlCommandDef(TMCC2_EFFECTS_CONTROL_SUBWAY_LEFT_DOOR_OPEN)
    SUBWAY_RIGHT_DOOR_CLOSE = EffectsControlCommandDef(TMCC2_EFFECTS_CONTROL_SUBWAY_RIGHT_DOOR_CLOSE)
    SUBWAY_RIGHT_DOOR_OPEN = EffectsControlCommandDef(TMCC2_EFFECTS_CONTROL_SUBWAY_RIGHT_DOOR_OPEN)
    SUBWAY_BOTH_DOOR_CLOSE = EffectsControlCommandDef(TMCC2_EFFECTS_CONTROL_SUBWAY_BOTH_DOOR_CLOSE)
    SUBWAY_BOTH_DOOR_OPEN = EffectsControlCommandDef(TMCC2_EFFECTS_CONTROL_SUBWAY_BOTH_DOOR_OPEN)
    COAL_EMPTY = EffectsControlCommandDef(TMCC2_EFFECTS_CONTROL_COAL_EMPTY)
    COAL_FULL = EffectsControlCommandDef(TMCC2_EFFECTS_CONTROL_COAL_FULL)
    COAL_EMPTYING = EffectsControlCommandDef(TMCC2_EFFECTS_CONTROL_COAL_EMPTYING)
    COAL_FILLING = EffectsControlCommandDef(TMCC2_EFFECTS_CONTROL_COAL_FILLING)


"""
    Word #2 - Lighting controls (index 0xD)
"""
TMCC2_LIGHTING_CONTROL_CAB_LIGHT_AUTO: int = 0xF2
TMCC2_LIGHTING_CONTROL_CAB_LIGHT_OFF: int = 0xF0
TMCC2_LIGHTING_CONTROL_CAB_LIGHT_ON: int = 0xF1
TMCC2_LIGHTING_CONTROL_CAB_LIGHT_TOGGLE: int = 0xF3
TMCC2_LIGHTING_CONTROL_CAR_LIGHT_AUTO: int = 0xFA
TMCC2_LIGHTING_CONTROL_CAR_LIGHT_OFF: int = 0xF8
TMCC2_LIGHTING_CONTROL_CAR_LIGHT_ON: int = 0xF9
TMCC2_LIGHTING_CONTROL_CAR_LIGHT_TOGGLE: int = 0xFB
TMCC2_LIGHTING_CONTROL_DITCH_LIGHT_OFF: int = 0xC0
TMCC2_LIGHTING_CONTROL_DITCH_LIGHT_OFF_PULSE_ON_WITH_HORN: int = 0xC1
TMCC2_LIGHTING_CONTROL_DITCH_LIGHT_ON: int = 0xC3
TMCC2_LIGHTING_CONTROL_DITCH_LIGHT_ON_PULSE_OFF_WITH_HORN: int = 0xC2
TMCC2_LIGHTING_CONTROL_DOGHOUSE_LIGHT_OFF: int = 0xA0
TMCC2_LIGHTING_CONTROL_DOGHOUSE_LIGHT_ON: int = 0xA1
TMCC2_LIGHTING_CONTROL_GROUND_LIGHT_AUTO: int = 0xD2
TMCC2_LIGHTING_CONTROL_GROUND_LIGHT_OFF: int = 0xD0
TMCC2_LIGHTING_CONTROL_GROUND_LIGHT_ON: int = 0xD1
TMCC2_LIGHTING_CONTROL_HAZARD_LIGHT_OFF: int = 0xB0
TMCC2_LIGHTING_CONTROL_HAZARD_LIGHT_ON: int = 0xB1
TMCC2_LIGHTING_CONTROL_HAZARD_LIGHT_AUTO: int = 0xB2
TMCC2_LIGHTING_CONTROL_LOCO_MARKER_LIGHT_OFF: int = 0xC8
TMCC2_LIGHTING_CONTROL_LOCO_MARKER_LIGHT_ON: int = 0xC9
TMCC2_LIGHTING_CONTROL_LOCO_MARKER_LIGHT_AUTO: int = 0xCA
TMCC2_LIGHTING_CONTROL_MARS_LIGHT_OFF: int = 0xE8
TMCC2_LIGHTING_CONTROL_MARS_LIGHT_ON: int = 0xE9
TMCC2_LIGHTING_CONTROL_RULE_17_AUTO: int = 0xF6
TMCC2_LIGHTING_CONTROL_RULE_17_OFF: int = 0xF4
TMCC2_LIGHTING_CONTROL_RULE_17_ON: int = 0xF5
TMCC2_LIGHTING_CONTROL_STROBE_LIGHT_OFF: int = 0xE0
TMCC2_LIGHTING_CONTROL_STROBE_LIGHT_ON_DOUBLE_FLASH: int = 0xE2
TMCC2_LIGHTING_CONTROL_STROBE_LIGHT_ON_SINGLE_FLASH: int = 0xE1
TMCC2_LIGHTING_CONTROL_TENDER_MARKER_LIGHT_OFF: int = 0xCC
TMCC2_LIGHTING_CONTROL_TENDER_MARKER_LIGHT_ON: int = 0xCD
TMCC2_LIGHTING_CONTROL_WORK_LIGHT_OFF: int = 0xD8
TMCC2_LIGHTING_CONTROL_WORK_LIGHT_ON: int = 0xD9
TMCC2_LIGHTING_CONTROL_WORK_LIGHT_AUTO: int = 0xDA


class LightingControlCommandDef(MultiByteCommandDef):
    def __init__(
        self,
        command_bits: int,
        d_min: int = 0,
        d_max: int = 0,
        interval: int = None,
        noop: bool = False,
    ) -> None:
        super().__init__(
            TMCC2ParameterIndex.LIGHTING_CONTROLS,
            command_bits,
            d_min=d_min,
            d_max=d_max,
            interval=interval,
            noop=noop,
        )


@unique
class TMCC2LightingControl(TMCC2ParameterEnum):
    CAB_AUTO = LightingControlCommandDef(TMCC2_LIGHTING_CONTROL_CAB_LIGHT_AUTO)
    CAB_OFF = LightingControlCommandDef(TMCC2_LIGHTING_CONTROL_CAB_LIGHT_OFF)
    CAB_ON = LightingControlCommandDef(TMCC2_LIGHTING_CONTROL_CAB_LIGHT_ON)
    CAB_TOGGLE = LightingControlCommandDef(TMCC2_LIGHTING_CONTROL_CAB_LIGHT_TOGGLE)
    CAR_AUTO = LightingControlCommandDef(TMCC2_LIGHTING_CONTROL_CAR_LIGHT_AUTO)
    CAR_OFF = LightingControlCommandDef(TMCC2_LIGHTING_CONTROL_CAR_LIGHT_OFF)
    CAR_ON = LightingControlCommandDef(TMCC2_LIGHTING_CONTROL_CAR_LIGHT_ON)
    CAR_TOGGLE = LightingControlCommandDef(TMCC2_LIGHTING_CONTROL_CAR_LIGHT_TOGGLE)
    DITCH_OFF = LightingControlCommandDef(TMCC2_LIGHTING_CONTROL_DITCH_LIGHT_OFF)
    DITCH_OFF_PULSE_ON_WITH_HORN = LightingControlCommandDef(TMCC2_LIGHTING_CONTROL_DITCH_LIGHT_OFF_PULSE_ON_WITH_HORN)
    DITCH_ON = LightingControlCommandDef(TMCC2_LIGHTING_CONTROL_DITCH_LIGHT_ON)
    DITCH_ON_PULSE_OFF_WITH_HORN = LightingControlCommandDef(TMCC2_LIGHTING_CONTROL_DITCH_LIGHT_ON_PULSE_OFF_WITH_HORN)
    DOGHOUSE_OFF = LightingControlCommandDef(TMCC2_LIGHTING_CONTROL_DOGHOUSE_LIGHT_OFF)
    DOGHOUSE_ON = LightingControlCommandDef(TMCC2_LIGHTING_CONTROL_DOGHOUSE_LIGHT_ON)
    GROUND_AUTO = LightingControlCommandDef(TMCC2_LIGHTING_CONTROL_GROUND_LIGHT_AUTO)
    GROUND_OFF = LightingControlCommandDef(TMCC2_LIGHTING_CONTROL_GROUND_LIGHT_OFF)
    GROUND_ON = LightingControlCommandDef(TMCC2_LIGHTING_CONTROL_GROUND_LIGHT_ON)
    HAZARD_AUTO = LightingControlCommandDef(TMCC2_LIGHTING_CONTROL_HAZARD_LIGHT_AUTO)
    HAZARD_OFF = LightingControlCommandDef(TMCC2_LIGHTING_CONTROL_HAZARD_LIGHT_OFF)
    HAZARD_ON = LightingControlCommandDef(TMCC2_LIGHTING_CONTROL_HAZARD_LIGHT_ON)
    LOCO_MARKER_AUTO = LightingControlCommandDef(TMCC2_LIGHTING_CONTROL_LOCO_MARKER_LIGHT_AUTO)
    LOCO_MARKER_OFF = LightingControlCommandDef(TMCC2_LIGHTING_CONTROL_LOCO_MARKER_LIGHT_OFF)
    LOCO_MARKER_ON = LightingControlCommandDef(TMCC2_LIGHTING_CONTROL_LOCO_MARKER_LIGHT_ON)
    MARS_OFF = LightingControlCommandDef(TMCC2_LIGHTING_CONTROL_MARS_LIGHT_OFF)
    MARS_ON = LightingControlCommandDef(TMCC2_LIGHTING_CONTROL_MARS_LIGHT_ON)
    RULE_17_AUTO = LightingControlCommandDef(TMCC2_LIGHTING_CONTROL_RULE_17_AUTO)
    RULE_17_OFF = LightingControlCommandDef(TMCC2_LIGHTING_CONTROL_RULE_17_OFF)
    RULE_17_ON = LightingControlCommandDef(TMCC2_LIGHTING_CONTROL_RULE_17_ON)
    STROBE_LIGHT_OFF = LightingControlCommandDef(TMCC2_LIGHTING_CONTROL_STROBE_LIGHT_OFF)
    STROBE_LIGHT_ON = LightingControlCommandDef(TMCC2_LIGHTING_CONTROL_STROBE_LIGHT_ON_SINGLE_FLASH)
    STROBE_LIGHT_ON_DOUBLE = LightingControlCommandDef(TMCC2_LIGHTING_CONTROL_STROBE_LIGHT_ON_DOUBLE_FLASH)
    TENDER_MARKER_OFF = LightingControlCommandDef(TMCC2_LIGHTING_CONTROL_TENDER_MARKER_LIGHT_OFF)
    TENDER_MARKER_ON = LightingControlCommandDef(TMCC2_LIGHTING_CONTROL_TENDER_MARKER_LIGHT_ON)
    WORK_AUTO = LightingControlCommandDef(TMCC2_LIGHTING_CONTROL_WORK_LIGHT_AUTO)
    WORK_OFF = LightingControlCommandDef(TMCC2_LIGHTING_CONTROL_WORK_LIGHT_OFF)
    WORK_ON = LightingControlCommandDef(TMCC2_LIGHTING_CONTROL_WORK_LIGHT_ON)


# R4LC Commands; modify Engine eeprom
@unique
class UnitAssignment(Mixins, IntEnum):
    SINGLE_FORWARD = 0b000
    SINGLE_REVERSE = 0b100
    HEAD_FORWARD = 0b001
    HEAD_REVERSE = 0b101
    MIDDLE_FORWARD = 0b010
    MIDDLE_REVERSE = 0b110
    TAIL_FORWARD = 0b011
    TAIL_REVERSE = 0b111

    @property
    def is_forward(self) -> bool:
        return self.value & 0b100 == 0b000

    @property
    def is_reverse(self) -> bool:
        return self.value & 0b100 == 0b100

    @property
    def is_head(self) -> bool:
        return self.value & 0b011 == 0b001

    @property
    def is_middle(self) -> bool:
        return self.value & 0b011 == 0b010

    @property
    def is_tail(self) -> bool:
        return self.value & 0b011 == 0b011

    @property
    def is_single(self) -> bool:
        return self.value & 0b011 == 0b000

    @property
    def position(self) -> str:
        if self.is_single:
            return "Single"
        elif self.is_head:
            return "Head"
        elif self.is_middle:
            return "Middle"
        elif self.is_tail:
            return "Tail"
        else:
            return "NA"

    @property
    def direction(self) -> str:
        if self.is_forward:
            return "Forward"
        elif self.is_reverse:
            return "Reverse"
        else:
            return "NA"


# index values,
TMCC2_SET_ENGINE_ADDRESS_INDEX: int = 0x40
TMCC2_SET_ENGINE_STALL_INDEX: int = 0x41
TMCC2_SET_TRAIN_ADDRESS_INDEX: int = 0x42
TMCC2_SET_TRAIN_UNIT_INDEX: int = 0x43
TMCC2_SET_MAX_SPEED_INDEX: int = 0x44
TMCC2_SET_DIRECTION_INDEX: int = 0x45
TMCC2_SET_FLAGS_INDEX: int = 0x46
TMCC2_SET_CONTROL_INDEX: int = 0x47
TMCC2_SET_ENGINE_TYPE_INDEX: int = 0x48
TMCC2_SET_SPEED_RESOLUTION_INDEX: int = 0x49
TMCC2_SET_VARIABLE_RESOLUTION_INDEX: int = 0x4A
TMCC2_SET_INDIRECT_INDEX: int = 0x4F


@unique
class TMCC2R4LCIndex(Mixins, IntEnum):
    ENGINE_ADDRESS = TMCC2_SET_ENGINE_ADDRESS_INDEX
    ENGINE_STALL = TMCC2_SET_ENGINE_STALL_INDEX
    TRAIN_ADDRESS = TMCC2_SET_TRAIN_ADDRESS_INDEX
    TRAIN_UNIT = TMCC2_SET_TRAIN_UNIT_INDEX
    MAX_SPEED = TMCC2_SET_MAX_SPEED_INDEX
    DIRECTION = TMCC2_SET_DIRECTION_INDEX
    FLAGS = TMCC2_SET_FLAGS_INDEX
    CONTROL = TMCC2_SET_CONTROL_INDEX
    ENGINE_TYPE = TMCC2_SET_ENGINE_TYPE_INDEX
    SPEED_RESOLUTION = TMCC2_SET_SPEED_RESOLUTION_INDEX
    VARIABLE_RESOLUTION = TMCC2_SET_VARIABLE_RESOLUTION_INDEX
    INDIRECT = TMCC2_SET_INDIRECT_INDEX


class R4LCCommandDef(MultiByteCommandDef):
    def __init__(
        self,
        command_bits: int,
        d_min: int = 0,
        d_max: int = 0,
        interval: int = None,
        noop: bool = False,
    ) -> None:
        super().__init__(
            TMCC2ParameterIndex.R4LC,
            command_bits,
            d_min=d_min,
            d_max=d_max,
            interval=interval,
            noop=noop,
        )


# I don't like using the same constants for the "data" enums, but for now...
# This will probably stick, as we are really only going to use these to
# echo commands
@unique
class TMCC2R4LCEnum(TMCC2MultiByteEnum):
    ENGINE_ADDRESS = R4LCCommandDef(TMCC2_SET_ENGINE_ADDRESS_INDEX, d_min=1, d_max=99)
    ENGINE_STALL = R4LCCommandDef(TMCC2_SET_ENGINE_STALL_INDEX)
    TRAIN_ADDRESS = R4LCCommandDef(TMCC2_SET_TRAIN_ADDRESS_INDEX, d_max=99)
    TRAIN_UNIT = R4LCCommandDef(TMCC2_SET_TRAIN_UNIT_INDEX, d_max=7)
    MAX_SPEED = R4LCCommandDef(TMCC2_SET_MAX_SPEED_INDEX, d_min=32, d_max=200)
    DIRECTION = R4LCCommandDef(TMCC2_SET_DIRECTION_INDEX, d_max=255)
    FLAGS = R4LCCommandDef(TMCC2_SET_FLAGS_INDEX, d_max=63)
    CONTROL = R4LCCommandDef(TMCC2_SET_CONTROL_INDEX, d_max=1)
    ENGINE_TYPE = R4LCCommandDef(TMCC2_SET_ENGINE_TYPE_INDEX, d_max=7)
    SPEED_RESOLUTION = R4LCCommandDef(TMCC2_SET_SPEED_RESOLUTION_INDEX, d_max=7)
    VARIABLE_RESOLUTION = R4LCCommandDef(TMCC2_SET_VARIABLE_RESOLUTION_INDEX)
    INDIRECT = R4LCCommandDef(TMCC2_SET_INDIRECT_INDEX)


#
# Variable length Multibyte commands
#
class VariableCommandDef(MultiByteCommandDef):
    __metaclass__ = abc.ABCMeta

    def __init__(
        self,
        command_bits: int,
        num_data_bytes: int,
        data_bytes: List[int] = None,
        code: VolumeCode = None,
        d_min: int = 0,
        d_max: int = 0,
        is_abstract: bool = False,
    ) -> None:
        super().__init__(TMCC2ParameterIndex.VARIABLE_LENGTH_COMMAND, command_bits, d_min=d_min, d_max=d_max)
        self._code = code
        self._num_data_bytes = num_data_bytes
        self._data_bytes = data_bytes
        self._is_abstract = is_abstract

    @property
    def num_data_bytes(self) -> int:
        return self._num_data_bytes

    @property
    def lsb(self) -> int:
        return 0x00FF & self.bits

    @property
    def msb(self) -> int:
        return (0xFF00 & self.bits) >> 8

    @property
    def is_abstract(self) -> bool:
        return self._is_abstract

    @property
    def has_volume_code(self) -> bool:
        return self.bits == TMCC2_SET_VOLUME_DIRECT

    @property
    def volume_code(self) -> VolumeCode:
        return self._code


TMCC2_VOLUME_DIRECT_MASTER: int = 0xC8
TMCC2_VOLUME_DIRECT_HORN: int = 0xC9
TMCC2_VOLUME_DIRECT_BELL: int = 0xCB
TMCC2_VOLUME_DIRECT_DIALOG: int = 0xCD
TMCC2_VOLUME_DIRECT_BLEND: int = 0xCF


class VolumeCode(Mixins, IntEnum):
    MASTER = TMCC2_VOLUME_DIRECT_MASTER
    HORN = TMCC2_VOLUME_DIRECT_HORN
    BELL = TMCC2_VOLUME_DIRECT_BELL
    DIALOG = TMCC2_VOLUME_DIRECT_DIALOG
    BLEND = TMCC2_VOLUME_DIRECT_BLEND

    def __repr__(self) -> str:
        return f"[{self.name}: {self.value:02X}]"

    @property
    def as_bytes(self) -> bytes:
        return bytes([self.value])


TMCC2_SET_MASTER_VOLUME: int = 0xB000
TMCC2_SET_BLEND_VOLUME: int = 0xB001
TMCC2_SET_VOLUME_DIRECT: int = 0xB004
TMCC2_BLE_GET_INFO: int = 0xC000
TMCC2_BLE_GET_STATUS: int = 0xC001
TMCC2_DCDS_FACTORY_DEFAULT = 0xF000
TMCC2_DCDS_STORE = 0xF001


class TMCC2VariableEnum(TMCC2MultiByteEnum):
    MASTER_VOLUME = VariableCommandDef(TMCC2_SET_MASTER_VOLUME, 1, d_min=0, d_max=255)
    BLEND_VOLUME = VariableCommandDef(TMCC2_SET_BLEND_VOLUME, 1, d_min=0, d_max=255)
    VOLUME_DIRECT = VariableCommandDef(TMCC2_SET_VOLUME_DIRECT, 2, is_abstract=True)
    MASTER_DIRECT = VariableCommandDef(TMCC2_SET_VOLUME_DIRECT, 2, code=VolumeCode.MASTER, d_min=0, d_max=7)
    HORN_DIRECT = VariableCommandDef(TMCC2_SET_VOLUME_DIRECT, 2, code=VolumeCode.HORN, d_min=0, d_max=7)
    BELL_DIRECT = VariableCommandDef(TMCC2_SET_VOLUME_DIRECT, 2, code=VolumeCode.BELL, d_min=0, d_max=7)
    DIALOG_DIRECT = VariableCommandDef(TMCC2_SET_VOLUME_DIRECT, 2, code=VolumeCode.DIALOG, d_min=0, d_max=7)
    BLEND_DIRECT = VariableCommandDef(TMCC2_SET_VOLUME_DIRECT, 2, code=VolumeCode.BLEND, d_min=0, d_max=15)
    FACTORY_DEFAULT = VariableCommandDef(TMCC2_DCDS_FACTORY_DEFAULT, 2, [0xEF, 0xBF])
    STORE = VariableCommandDef(TMCC2_DCDS_FACTORY_DEFAULT, 2, [0xEF, 0xBF])
    GET_INFO = VariableCommandDef(TMCC2_BLE_GET_INFO, 4, [0x0, 0x0, 0x0, 0x0])
    GET_STATUS = VariableCommandDef(TMCC2_BLE_GET_STATUS, 5, [0x0, 0x0, 0x0, 0x0, 0x0])

    # noinspection PyTypeChecker
    def by_volume_code(self, volume_code: VolumeCode, raise_exception: bool = False) -> "TMCC2VariableEnum":
        for cmd_enum in self.__class__.__members__.values():
            if cmd_enum.volume_code == volume_code:
                return cmd_enum
        if raise_exception:
            raise ValueError(f"No volume code {volume_code} found in {self.__class__.__name__}")
        return None

    @property
    def num_data_bytes(self) -> int:
        return self.value.num_data_bytes

    @property
    def is_abstract(self) -> bool:
        return self.value.is_abstract

    @property
    def has_volume_code(self) -> bool:
        return self.value.bits == TMCC2_SET_VOLUME_DIRECT

    @property
    def volume_code(self) -> VolumeCode:
        return self.value.volume_code
